import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://bprp-qa.shadhinlab.xyz/")
    page.get_by_role("heading", name="Test this agency").click()
    page.get_by_role("link", name="Talent", exact=True).click()
    page.get_by_role("link", name="Talent list").click()
    page.get_by_role("button", name="Add Candidate").click()
    page.get_by_role("button", name="Save").click()
    expect(page.get_by_text("First name is required")).to_be_visible()
    expect(page.get_by_text("Last name is required")).to_be_visible()
    expect(page.get_by_text("Gender is required")).to_be_visible()
    expect(page.get_by_text("Job title is required.")).to_be_visible()
    expect(page.get_by_text("Date of birth is required")).to_be_visible()
    expect(page.get_by_text("Japanese level is required.")).to_be_visible()
    expect(page.get_by_text("English level is required.")).to_be_visible()
    expect(page.get_by_text("Location is required.")).to_be_visible()
    page.get_by_text("Upload Profile Picture").click()
    page.get_by_text("Upload CV file (optional)").click()
    expect(page.get_by_role("button", name="Cancel")).to_be_visible()
    expect(page.get_by_role("button", name="Save")).to_be_visible()
    expect(page.get_by_role("heading", name="Add New Talent")).to_be_visible()
    page.get_by_role("textbox", name="CV Name").click()
    page.get_by_role("textbox", name="CV Name").click()
    page.get_by_role("textbox", name="CV Name").fill("djh gfsdhgfd sh hgsd")
    page.locator("div:nth-child(2) > .searchable-select > .select-trigger").click()
    page.get_by_text("Aymara").click()
    page.get_by_text("First Name", exact=True).click()
    page.get_by_role("textbox", name="First Name").fill("foyez")
    page.get_by_text("Last Name", exact=True).click()
    page.get_by_role("textbox", name="Last Name").fill("kabir")
    page.locator("div").filter(has_text=re.compile(r"^Gender Gender is required$")).locator("div").nth(2).click()
    page.locator("div").filter(has_text=re.compile(r"^Male$")).click()
    page.get_by_role("textbox", name="Job Title").click()
    page.get_by_role("textbox", name="Job Title").fill("gfsdgsaghd hjsdjgfdsigfisdfg")
    page.locator("input[name=\"date_of_birth\"]").click()
    page.get_by_text("August2025").click()
    page.locator(".react-datepicker__year-read-view--down-arrow").click()
    page.get_by_text("1998").click()
    page.locator("div").filter(has_text=re.compile(r"^August1998$")).locator("span").first.click()
    page.get_by_text("January").click()
    page.get_by_role("option", name="Choose Friday, January 16th,").click()
    page.locator("div").filter(has_text=re.compile(r"^Japanese Level Japanese level is required\.$")).locator("div").nth(1).click()
    page.locator("div").filter(has_text=re.compile(r"^Conversational$")).click()
    page.locator("div").filter(has_text=re.compile(r"^English Level English level is required\.$")).locator("div").nth(1).click()
    page.locator("div").filter(has_text=re.compile(r"^Fluent$")).click()
    page.get_by_role("textbox", name="Location").click()
    page.get_by_role("textbox", name="Location").fill("hagfsdhgasfdhastdrsd   fsd sdfu fsducf sdfcuy sdfcusdf ucfsduc fsds fcgsdfc sfcg sfgc sdgdcf shgd fcsdfcgfsdg csdygc fsdgf cfsdcf sdgc hgc fshd fchgZ FChgsdf chfxyg sducf sdcf sghd c zX FChg sdfhcg fd")
    page.get_by_role("button", name="Save").click()
    page.get_by_text("Talent Created Successfully").click()
    page.get_by_text("Talent Created Successfully").click()
    page.get_by_role("button", name="View Details").click()
    expect(page.get_by_text("Home>Talent>Talent Details")).to_be_visible()
    page.locator("div").filter(has_text=re.compile(r"^Personal InfoEdit$")).get_by_role("button").nth(1).click()
    page.get_by_role("button", name="Add CV").click()
    page.get_by_role("textbox", name="First Name").click()
    page.get_by_role("textbox", name="First Name").fill("foyez dhfgds")
    page.get_by_role("textbox", name="Last Name").click()
    page.get_by_role("textbox", name="Last Name").fill("kabir djgfjds")
    page.locator("input[name=\"dob\"]").click()
    page.get_by_role("option", name="Choose Friday, January 16th,").click()
    page.locator(".trigger-content").first.click()
    page.get_by_text("AAA").click()
    page.get_by_role("textbox", name="Location").click()
    page.get_by_role("textbox", name="Location").click()
    page.get_by_role("textbox", name="Location").fill(" sdfcuy sdfcusdf ucfsduc fsds fcgsdfc sfcg sfgc sdgdcf shgd fcsdfcgfsdg csdygc fsdgf cfsdcf sdgc hgc fshd fchgZ FChgsdf chfxyg sducf sdcf sghd c zX FChg sdfhcg fd")
    page.get_by_role("textbox", name="Location").press("ArrowRight")
    page.get_by_role("textbox", name="Location").fill("sdfcuy sdfcusdf ucfsduc fsds fcgsdfc sfcg sfgc sdgdcf shgd fcsdfcgfsdg csdygc fsdgf cfsdcf sdgc hgc fshd fchgZ FChgsdf chfxyg sducf sdcf sghd c zX FChg sdfhcg fd")
    page.get_by_role("button", name="Add Education").click()
    page.get_by_role("textbox", name="School").click()
    page.get_by_role("textbox", name="School").fill("NSU")
    page.get_by_role("textbox", name="Degree").click()
    page.get_by_role("textbox", name="Degree").fill("BSC")
    page.locator("input[name=\"education.0.start_year\"]").click()
    page.get_by_text("2018").click()
    page.locator("input[name=\"education.0.end_year\"]").click()
    page.get_by_text("2025").click()
    expect(page.get_by_role("button", name="Remove").first).to_be_visible()
    page.get_by_role("button", name="Remove").first.click()
    page.get_by_role("button", name="Add Education").click()
    expect(page.get_by_text("School is required")).to_be_visible()
    expect(page.get_by_text("Degree is required")).to_be_visible()
    page.get_by_role("button", name="Save", exact=True).click()
    expect(page.get_by_text("CV name is required")).to_be_visible()
    page.get_by_text("CV language is required").click()
    expect(page.get_by_text("CV language is required")).to_be_visible()
    page.get_by_text("Upload CV file").click()
    page.get_by_role("button", name="Add CV").click()
    page.get_by_role("button", name="Add CV").click()
    page.get_by_role("button", name="Remove").nth(3).click()
    page.get_by_role("button", name="Remove").nth(1).click()
    page.get_by_role("button", name="Remove").first.click()
    page.get_by_role("button", name="Remove").click()
    page.get_by_role("button", name="Save", exact=True).click()
    page.get_by_text("Company info updated").click()
    page.locator(".flex.items-start").first.click()
